### ISSUE TITLE
There is already a popular HTTP request router called mux

### ISSUE THREAD

**Issue by peterbourgon** [donutloop/mux#4]
Please consider renaming the project.

**Comment by donutloop** [comment]
Mux is a concept not brandOn Dec 5, 2016 7:16 PM, Peter Bourgon <notifications@github.com> wrote:Please consider renaming the project.

**Comment by donutloop** [comment]
Hello, If you think that is issue than i well doing itOn Dec 5, 2016 7:30 PM, Marcel Franke <info@marcel-edmund-franke.de> wrote:Mux is a concept not brandOn Dec 5, 2016 7:16 PM, Peter Bourgon <notifications@github.com> wrote:Please consider renaming the project.

**Comment by donutloop** [comment]
They called it in the standard lib mux as well. Is this a huge issue ?On Dec 5, 2016 7:31 PM, Marcel Franke <info@marcel-edmund-franke.de> wrote:Hello, If you think that is issue than i well doing itOn Dec 5, 2016 7:30 PM, Marcel Franke <info@marcel-edmund-franke.de> wrote:Mux is a concept not brandOn Dec 5, 2016 7:16 PM, Peter Bourgon <notifications@github.com> wrote:Please consider renaming the project.

**Comment by peterbourgon** [comment]
Muxing is a concept, but calling your project "mux" conflicts with a well-established project, and confuses users neednessly. Of course, you're free to do whatever you like.

**Comment by donutloop** [comment]
Before i launched my project on github. i have searched on github with a key word "mux". I have found many router projects with this name and my conclusion was than that it's ok.

the namespace is different "github/donutloop/mux"
